insert into Users(id, fullname, username, password, role) values(1, "Administrator", "admin", "test", "ADMIN")
insert into Users(id, fullname, username, password, role) values(2, "User", "user", "test", "USER")
insert into Trade(id, account, type) values(1, "accountTest", "typeTest")
insert into Rulename(id, name, description) values(1, "nameTest", "descriptionTest")
insert into Rating(id, fitch_rating, order_number) values(1, "fitchRating", 2)
insert into Curvepoint(id, curve_id, value) values(1, 2, 3)
insert into Bidlist(id, account, deal_name) values(1, "accountTest", "dealNameTest")